name: Deploy wandbox.org

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Register SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519
    - name: Add SSH config
      run: |
        echo "Host kennel-root" >> $HOME/.ssh/config
        echo "    HostName 49.212.130.73" >> $HOME/.ssh/config
        echo "    User root" >> $HOME/.ssh/config
        ssh-keyscan -H 49.212.130.73 >> $HOME/.ssh/known_hosts
        echo "Host cattleshed-root" >> $HOME/.ssh/config
        echo "    HostName 153.121.40.132" >> $HOME/.ssh/config
        echo "    User root" >> $HOME/.ssh/config
        ssh-keyscan -H 153.121.40.132 >> $HOME/.ssh/known_hosts
    - name: apt install
      run: sudo apt-get install -y libcap-dev
    - name: Get cached tools
      id: cache-tools
      uses: actions/cache@v1
      with:
        path: _install
        key: install-tools
    - name: Install tools
      run: ./install_tools.sh --release
    - name: Package kennel
      run: |
        ./package.sh kennel production
    - name: Package cattleshed
      run: |
        ./package.sh cattleshed production
    - name: Deploy kennel to wandbox.org
      run: |
        ./deploy.sh kennel-root kennel production
    - name: Deploy cattleshed to wandbox.org
      run: |
        ./deploy.sh cattleshed-root cattleshed production
